version: '3.2'

services:
  app-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-api:latest
    container_name: app-api-container
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    network_mode: 'host'
